ETISS 0.8.0: /home/travis/build/tum-ei-eda/etiss/src/IntegratedLibrary/gdb/GDBSystemWrapper.cpp File Reference
GDBSystemWrapper.cpp File Reference
implements a ETISS_System wrapper to enable breakpoints
#include <malloc.h>
#include "etiss/IntegratedLibrary/gdb/GDBServer.h"
Classes
struct ETISS_GDBSystem
Typedefs
typedef struct ETISS_GDBSystem ETISS_GDBSystem
Functions
etiss_int32 gdb_system_call_iread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
etiss_int32 gdb_system_call_iwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 gdb_system_call_dread (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 gdb_system_call_dwrite (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 gdb_system_call_dbg_read (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
etiss_int32 gdb_system_call_dbg_write (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
void gdb_system_call_syncTime (void *handle, ETISS_CPU *cpu)
Detailed Description
implements a ETISS_System wrapper to enable breakpoints
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://gitlab.lrz.de/de-tum-ei-eda-open/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file GDBSystemWrapper.cpp.
Typedef Documentation
ETISS_GDBSystem
typedef struct ETISS_GDBSystem ETISS_GDBSystem
Definition at line 68 of file GDBSystemWrapper.cpp.
Function Documentation
gdb_system_call_dbg_read()
etiss_int32 gdb_system_call_dbg_read (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 119 of file GDBSystemWrapper.cpp.
References ETISS_System::dbg_read, ETISS_System::handle, and ETISS_GDBSystem::sys_.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_dbg_write()
etiss_int32 gdb_system_call_dbg_write (void * handle, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 126 of file GDBSystemWrapper.cpp.
References ETISS_System::dbg_write, ETISS_System::handle, and ETISS_GDBSystem::sys_.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_dread()
etiss_int32 gdb_system_call_dread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 94 of file GDBSystemWrapper.cpp.
References ETISS_System::dread, ETISS_System::handle, etiss::plugin::gdb::Server::preMemoryAccessCallback(), ETISS_GDBSystem::server_, ETISS_GDBSystem::sys_, and unlikely.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_dwrite()
etiss_int32 gdb_system_call_dwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 106 of file GDBSystemWrapper.cpp.
References ETISS_System::dwrite, ETISS_System::handle, etiss::plugin::gdb::Server::preMemoryAccessCallback(), ETISS_GDBSystem::server_, ETISS_GDBSystem::sys_, and unlikely.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_iread()
etiss_int32 gdb_system_call_iread (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint32 length)
Definition at line 70 of file GDBSystemWrapper.cpp.
References ETISS_System::handle, ETISS_System::iread, etiss::plugin::gdb::Server::preMemoryAccessCallback(), ETISS_GDBSystem::server_, ETISS_GDBSystem::sys_, and unlikely.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_iwrite()
etiss_int32 gdb_system_call_iwrite (void * handle, ETISS_CPU * cpu, etiss_uint64 addr, etiss_uint8 * buffer, etiss_uint32 length)
Definition at line 81 of file GDBSystemWrapper.cpp.
References ETISS_System::handle, ETISS_System::iwrite, etiss::plugin::gdb::Server::preMemoryAccessCallback(), ETISS_GDBSystem::server_, ETISS_GDBSystem::sys_, and unlikely.
Referenced by etiss::plugin::gdb::Server::wrap().
gdb_system_call_syncTime()
void gdb_system_call_syncTime (void * handle, ETISS_CPU * cpu)
Definition at line 133 of file GDBSystemWrapper.cpp.
References ETISS_System::handle, ETISS_System::syncTime, and ETISS_GDBSystem::sys_.
Referenced by etiss::plugin::gdb::Server::wrap().