ETISS 0.8.0: ETISS_Internals
ETISS_Internals
Functions
void etiss::forceInitialization ()
Force the initialization of ETISS.
Detailed Description
Function Documentation
forceInitialization()
void etiss::forceInitialization ()
Force the initialization of ETISS.
This function is used by some ETISS functions to force initialization. The initialization is only performed if ETISS not initialized already.
See also
etiss::initialize
Definition at line 789 of file ETISS.cpp.
References etiss_initialize().
Referenced by etiss::addLibrary(), etiss::CPUCore::create(), and etiss::Initializer::Initializer().