# Generated on Wed, 16 Jul 2025 08:32:03 +0200.
#
# This file contains the CMake build info for the RV32IMACFDXCFU0 core architecture.

PROJECT(RV32IMACFDXCFU0)

SET(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
SET(CMAKE_INSTALL_RPATH "\$ORIGIN/../../include/jit/etiss/jit")

ADD_LIBRARY(${PROJECT_NAME} SHARED
	RV32IMACFDXCFU0Arch.cpp
	RV32IMACFDXCFU0ArchLib.cpp
	RV32IMACFDXCFU0ArchSpecificImp.cpp
	RV32IMACFDXCFU0Funcs.c
	RV32IMACFDXCFU0Instr.cpp
	RV32IMACFDXCFU0_RV32IInstr.cpp
	RV32IMACFDXCFU0_RV32ICInstr.cpp
	RV32IMACFDXCFU0_RV32MInstr.cpp
	RV32IMACFDXCFU0_RV32FInstr.cpp
	RV32IMACFDXCFU0_RV32FCInstr.cpp
	RV32IMACFDXCFU0_RV32DInstr.cpp
	RV32IMACFDXCFU0_RV32DCInstr.cpp
	RV32IMACFDXCFU0_ZifenceiInstr.cpp
	RV32IMACFDXCFU0_XCFU0Instr.cpp
	RV32IMACFDXCFU0_tum_csrInstr.cpp
	RV32IMACFDXCFU0_tum_retInstr.cpp
	RV32IMACFDXCFU0_RV32AInstr.cpp
	RV32IMACFDXCFU0_tum_rvaInstr.cpp
	RV32IMACFDXCFU0_tum_semihostingInstr.cpp
)

add_custom_command(
	TARGET ${PROJECT_NAME} POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy
		"${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Funcs.h"
		"${ETISS_BINARY_DIR}/include/jit/Arch/${PROJECT_NAME}"
)
INSTALL(FILES "${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Funcs.h" DESTINATION "include/jit/Arch/${PROJECT_NAME}")

ETISSPluginArch(${PROJECT_NAME})